### PR TITLE
Add avatars 6 13 2023

### PR DESCRIPTION
**Pull request by WizKingProd**
PC058: https://explorer.loopring.io/nft/0xebfc56ce1fc26b9c4ec3d58ea233327525f90738-0-0xb89897815d1c022a5278b70af124c8a84f926645-0x302ff52132d5729f608e6d5d0daf1c850f60237d2078c5aca17f43df507c830b-9

PC341: https://explorer.loopring.io/nft/0xebfc56ce1fc26b9c4ec3d58ea233327525f90738-0-0xb89897815d1c022a5278b70af124c8a84f926645-0xaa40bd2c34935969c370d5de419530fd63976a3cfa7919d2b30eadb0d32cd641-9

PC493: https://explorer.loopring.io/nft/0xebfc56ce1fc26b9c4ec3d58ea233327525f90738-0-0xb89897815d1c022a5278b70af124c8a84f926645-0x2684093e8291c34fc6eecf8ac635fb625d34729f71ca31810b475f1c8bc322ea-9

PC549: https://explorer.loopring.io/nft/0xebfc56ce1fc26b9c4ec3d58ea233327525f90738-0-0xb89897815d1c022a5278b70af124c8a84f926645-0x3a5a1e0305d3badb725085465b307366a4f15fd26eb81cfcb4574857db4d1460-9

PC997: https://explorer.loopring.io/nft/0xebfc56ce1fc26b9c4ec3d58ea233327525f90738-0-0xb89897815d1c022a5278b70af124c8a84f926645-0xba676e35ebaeda5cdab7765ac1e4523973a1cf12e1cce416544d2c1be26c23c2-9

PC1000: https://explorer.loopring.io/nft/0xebfc56ce1fc26b9c4ec3d58ea233327525f90738-0-0xb89897815d1c022a5278b70af124c8a84f926645-0xcee6596166b80f7a75813673dadc7508d4994c54e49b9740957233170c7d832a-9

SLB_cart005: https://lexplorer.io/nfts/0xdacc63155d5cb9aeca2c4ace959b7f6a64d5ce6b-0-0x5428a3363bb4a5a3c5c991f664346b1672f4c6c1-0xe2c610a40bf59f9b5cb3bc646bc767e53200c25a26940d1f9c8f5e1dd159726c-10

SLB_cart006: https://lexplorer.io/nfts/0xdacc63155d5cb9aeca2c4ace959b7f6a64d5ce6b-0-0x5428a3363bb4a5a3c5c991f664346b1672f4c6c1-0xef3c4d2b065f9a59adde2424f0cb8a02f8bf77655986e2c936abbba4bac4ae78-10

SLB_cart007: https://lexplorer.io/nfts/0xdacc63155d5cb9aeca2c4ace959b7f6a64d5ce6b-0-0x5428a3363bb4a5a3c5c991f664346b1672f4c6c1-0x47718ab5f343e019944a3ba0afe611a7fc43d4c4820830b0568083e199d384a9-10

### CODE REVIEW

**Comment by balkshamster** [comment]
tested and was able to load

**Comment by balkshamster** [comment]
SLB: 10
https://lexplorer.io/nfts/0xdacc63155d5cb9aeca2c4ace959b7f6a64d5ce6b-0-0x5428a3363bb4a5a3c5c991f664346b1672f4c6c1-0x214c5433256da27fd26f839588340d8cf965cfdcc1f7e9ca7e53c94718466b0e-10

**Comment by WizKingProd** [comment]
SLB: 011 https://lexplorer.io/nfts/0xdacc63155d5cb9aeca2c4ace959b7f6a64d5ce6b-0-0x5428a3363bb4a5a3c5c991f664346b1672f4c6c1-0xefbc96ecaa696501324a0802fa1da688df1dff6c8ea8e3c91e8cd6fb6917e02b-10

SLB: 012 https://lexplorer.io/nfts/0xdacc63155d5cb9aeca2c4ace959b7f6a64d5ce6b-0-0x5428a3363bb4a5a3c5c991f664346b1672f4c6c1-0xfa754d960bad700b8924942d2bb2a955440a8a54f72971de162f081c30db7465-10

**Comment by WizKingProd** [comment]
Will create new branch for tomorrow after merge is successful.

Add_Avatars_20230614

**Pull request merged**
